runtime: python37
# env: flexpython manage.py createsuperuser
entrypoint: gunicorn -b :$PORT config.wsgi

beta_settings:
    cloud_sql_instances: gothic-sequence-257518:us-central1:cloud-course

runtime_config:
  python_version: 3

handlers:

- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

vpc_access_connector:
  name: "projects/gothic-sequence-257518/locations/europe-west1/connectors/django-vue"
